"""add leverage item

Revision ID: 8c4f3b113420
Revises: a76a5dde6d18
Create Date: 2026-06-02 23:41:38.628455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c4f3b113420'
down_revision = 'a76a5dde6d18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('leverage_item', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('leverage_item')

    # ### end Alembic commands ###
