"""add custom bonus stats

Revision ID: a76a5dde6d18
Revises: 
Create Date: 2026-06-02 23:29:25.116675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a76a5dde6d18'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quarter_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ring_attack', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ft_drawn_bonus', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('loose_ball_dive', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gamemake_boost', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bench_datahack', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('captain_boost', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('charge_drawn', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quarter_stats', schema=None) as batch_op:
        batch_op.drop_column('charge_drawn')
        batch_op.drop_column('captain_boost')
        batch_op.drop_column('bench_datahack')
        batch_op.drop_column('gamemake_boost')
        batch_op.drop_column('loose_ball_dive')
        batch_op.drop_column('ft_drawn_bonus')
        batch_op.drop_column('ring_attack')

    # ### end Alembic commands ###
